# Generated by Django 5.0.2 on 2025-05-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_image_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_covers/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
