# Generated by Django 5.0.2 on 2025-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cover_image_recipe_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nom d'affichage public", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Votre localisation', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media',
            field=models.CharField(blank=True, help_text='Liens vers vos réseaux sociaux', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Votre site web personnel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Une brève description de vous'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='Vos spécialités culinaires'),
        ),
    ]
